### ISSUE TITLE
Submeter para o Moodle Plugins Directory

### ISSUE THREAD

**Issue by RafaelJovito** [CoticEaDIFRN/moodle_atto_justify#1]
- [x] Documentar como instalar
- [x] Documentar como desenvolver
- [x] Enviar para o Moodle Plugins Directory
- [x] Instalar no Acadêmico, Presencial e ProITEC 2018.

**Comment by RafaelJovito** [comment]
Documentação de instalação.

**Comment by kelsoncm** [comment]
A documentação de instalação está com erro, inclusive, mistura com a documentação de desenvolvimento.

**Comment by SueldoSales** [comment]
https://docs.moodle.org/dev/Plugin_contribution_checklist

**Comment by RafaelJovito** [comment]
https://moodle.org/plugins/atto_justify

**Comment by thauska** [comment]
Link quebrado. O moodle que uso é 3.3. O plugin não servirá?

**Comment by SueldoSales** [comment]
@thauska O link está quebrado porque o plugin ainda está em processo de aprovação pela equipe do Moodle, mas você pode baixar o plugin diretamente aqui pelo git. Quanto ao uso do mesmo no Moodle 3.3, existe a possibilidade que ele funcione sim, nós testamos apenas nas versões 3.4 e 3.5.

Se você testar na sua versão e funcionar, por favor nos comunique. Lembrando que o passo a passo para a instalação desse plugin se encontra no arquivo README deste repositório.

**Comment by thauska** [comment]
Bom dia. Fiz o teste no Moodle 3.3, mas precisei fazer uma alteração no arquivo version.php, alterando a versão requerida. Até o momento funcionou muito bem. Parabens pela iniciativa e obrigada pela contribuição. :+1:

**Comment by kelsoncm** [comment]
Se quiseres, podes nos enviar um Merge Request que aceitaremos.
